// SPDX-License-Identifier: MIT
// SSDV byte layer: header parse + RS(255,223) CCSDS encoder known-answer tests.
// KAT vectors generated by the Python reference mbdsdr_ai/fec.py (MIT).
#include <cstdint>
#include <cstdio>
#include <cstring>
#include "dsp/ssdv_packet.h"

using namespace mbdsdr::dsp;

static int failures = 0;
static void check(bool c, const char* m) {
    if (!c) { ++failures; std::printf("FAIL: %s\n", m); }
}

int main() {
    // --- Build the KAT FEC packet: flags=0xC9, imageId=0x2A, seq=3,
    //     width=8*(0x13+1)=168px, jpegLen-1 = 216 (0xD8 LE).
    uint8_t pkt[kSsdvPacketLen] = {0};
    pkt[0] = 0xC9; pkt[1] = 0x2A; pkt[2] = 0x03; pkt[3] = 0x13;
    pkt[4] = 0xD8; pkt[5] = 0x00;
    for (int i = 6; i < 223; ++i) pkt[i] = static_cast<uint8_t>((i * 37 + 11) & 0xFF);

    SsdvHeader h;
    check(parseSsdvHeader(pkt, sizeof(pkt), h), "header parses");
    check(h.fec == true, "FEC bit set");
    check(h.colour == true, "colour bit set");
    check(h.reliableEnd == true, "reliable-end bit set");
    check(h.packetType == 1, "packet type = 1");
    check(h.imageId == 0x2A, "image id");
    check(h.sequence == 3, "sequence number");
    check(h.widthPx == 160, "width decoded");
    check(h.jpegBytes == 217, "jpeg length decoded");

    size_t n = 0;
    const uint8_t* pl = ssdvJpegPayload(pkt, h, n);
    check(pl == pkt + 6 && n == 217, "payload slice correct");

    // Short buffer must be rejected.
    SsdvHeader bad;
    check(!parseSsdvHeader(pkt, 64, bad), "short packet rejected");

    // Uncoded packet: flags=0x41 (colour, no FEC), jpegBytes=250.
    uint8_t unc[kSsdvPacketLen] = {0};
    unc[0] = 0x41; unc[1] = 0x00; unc[2] = 0x00; unc[3] = 0x07;
    unc[4] = (uint8_t)(249 & 0xFF); unc[5] = 0x00;  // 250-1 = 249
    check(parseSsdvHeader(unc, sizeof(unc), bad), "uncoded header parses");
    check(bad.fec == false && bad.jpegBytes == 250 && bad.widthPx == 64,
          "uncoded fields");

    // --- RS(255,223) encoder KAT (parity cross-checked with Python fec.py).
    RsCcsds rs;
    uint8_t parity[32] = {0};
    rs.encode(pkt, parity);
    static const uint8_t kExpect[32] = {
        0xa0,0x5a,0x3c,0x51,0xf1,0x66,0x07,0xec,
        0x8c,0xb4,0x02,0xa9,0x99,0xdf,0x57,0x61,
        0xf8,0x8f,0xcb,0xdf,0xa7,0xac,0xfe,0x09,
        0xa7,0xf9,0x3b,0xa2,0x70,0x58,0x75,0x74};
    check(std::memcmp(parity, kExpect, 32) == 0, "RS parity matches Python KAT");

    // Determinism + all-zero message KAT (Python: all-zero -> zero parity).
    uint8_t zero[223] = {0};
    uint8_t p2[32] = {0xAA};
    rs.encode(zero, p2);
    bool allZero = true;
    for (int i = 0; i < 32; ++i) if (p2[i] != 0) allZero = false;
    check(allZero, "zero message -> zero parity (CCSDS KAT)");
    uint8_t p3[32];
    rs.encode(pkt, p3);
    check(std::memcmp(p3, parity, 32) == 0, "encode is deterministic");

    std::printf("ssdv_packet: %s\n", failures ? "FAILURES" : "all green");
    return failures ? 1 : 0;
}
