#!/usr/bin/env bash
# =====================================================================
#  MBDSDR paper submission packager (P2, phase 10).
#
#  Collects the controlled paper sources + the canonical 10 figures +
#  their CSVs/manifests into one self-contained submission folder.
#
#  DESIGN RULES (red lines):
#   * paper/ (repo root) is gitignored; figures/CSVs are regenerated by
#     the experiments/ scripts and are NOT committed. This script only
#     READS them and copies into an OUT folder the caller chooses.
#   * Only the 10 CANONICAL figures (origin/N/date matching main.md
#     Appendix + main.tex MIGRATE comments) are bundled. Smoke / debug
#     runs (small-N leftovers, e.g. N80/N160/N2/N18/N40) and the
#     unreferenced `recorded__N5` figure are EXCLUDED on purpose.
#   * refs.bib, the PDF and the final author block are NOT built here:
#     refs must be verified before bibliography creation (no fabricated
#     entries), and typesetting needs a real TeX environment with
#     IEEEtran.cls.
#
#  Usage:
#     bash tools/paper_package.sh [OUTDIR]
#     # default OUTDIR = ./paper_submission_package   (created fresh)
#
#  Exit 0 on success; prints a human manifest + writes MANIFEST.txt.
# =====================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTDIR="${1:-${REPO_ROOT}/paper_submission_package}"

PAPER_DIR="${REPO_ROOT}/docs/learn/phase7/paper"
FIG_DIR="${REPO_ROOT}/paper/experiments/figures"
CSV_DIR="${REPO_ROOT}/paper/experiments"

echo "MBDSDR paper packager"
echo "  repo root : ${REPO_ROOT}"
echo "  out dir   : ${OUTDIR}"

# Fresh, controlled output dir.
rm -rf "${OUTDIR}"
mkdir -p "${OUTDIR}/sources" "${OUTDIR}/figures" "${OUTDIR}/data"

copied=0
missing=0

# --- 1) controlled sources (tracked in docs/learn/phase7/paper/) -------
for f in main.md main.tex CHANGES.md README.md; do
  if [[ -f "${PAPER_DIR}/${f}" ]]; then
    cp -p "${PAPER_DIR}/${f}" "${OUTDIR}/sources/${f}"
    echo "  [src]  sources/${f}"
    copied=$((copied+1))
  else
    echo "  [MISS] sources/${f}"
    missing=$((missing+1))
  fi
done

# --- 2) the 10 canonical figures (explicit whitelist; see main.md App.) -
#    name  : figure basename (must exist verbatim on disk)
figs=(
  "ebno_decode_success__synthetic__N2400__20261001.png"            # Fig.1
  "rate_sweep_success__synthetic__N1400__20261002.png"             # Fig.2
  "rate_bandwidth_success__synthetic__N900__20261001.png"          # Fig.3
  "doppler_comp_success__synthetic__N3600__20261002.png"           # Fig.4
  "baseline_compare_amr__synthetic__N600__20261001.png"            # Fig.5
  "llm_baseline_amr__synthetic__N300__20261001.png"               # Fig.6 (LLM col PENDING)
  "amr_confusion_matrix__synthetic__N640__20261001.png"           # Fig.7
  "doppler_convergence__synthetic__N155__20261001.png"            # Fig.8
  "doppler_duration_convergence__synthetic__N6__20261001.png"      # Fig.9
  "agent_toolcall_stages__synthetic__N400__20261002.png"          # Fig.10
)
for fig in "${figs[@]}"; do
  if [[ -f "${FIG_DIR}/${fig}" ]]; then
    cp -p "${FIG_DIR}/${fig}" "${OUTDIR}/figures/${fig}"
    echo "  [fig]  figures/${fig}"
    copied=$((copied+1))
  else
    echo "  [MISS] figures/${fig}  (run the matching experiments/exp_*.py first)"
    missing=$((missing+1))
  fi
done

# --- 3) CSVs + per-run manifests (the provenance trail) -----------------
#    Whitelisted: only the artifacts the 10 experiments actually cite.
data=(
  "ebno_decode_success.csv"            "manifest_ebno_decode.json"      # Fig.1
  "rate_sweep_success.csv"             "manifest_rate_sweep.json"       # Fig.2
  "rate_bandwidth_success.csv"          "manifest_rate_bandwidth.json"   # Fig.3
  "doppler_comp_success.csv"           "manifest_doppler_comp.json"     # Fig.4
  "baseline_compare.csv"               "manifest_baseline.json"         # Fig.5
  "llm_baseline.csv"                   "manifest_llm_baseline.json"     # Fig.6
  "amr_confusion_matrix_snr10.csv"     "manifest_amr.json"              # Fig.7
  "doppler_convergence.csv"            "manifest_doppler.json"          # Fig.8
  "doppler_duration_convergence.csv"   "manifest_doppler_duration.json" # Fig.9
  "agent_toolcall_stage_summary.csv"    "manifest_agent_toolcall.json"   # Fig.10
  "agent_toolcall_detail.csv"           # Fig.10 supporting detail
  "agent_toolcall_requests.csv"        # Fig.10 supporting request suite
)
for d in "${data[@]}"; do
  if [[ -f "${CSV_DIR}/${d}" ]]; then
    cp -p "${CSV_DIR}/${d}" "${OUTDIR}/data/${d}"
    echo "  [data] data/${d}"
    copied=$((copied+1))
  else
    echo "  [MISS] data/${d}"
    missing=$((missing+1))
  fi
done

# --- 4) MANIFEST.txt ----------------------------------------------------
MANIFEST="${OUTDIR}/MANIFEST.txt"
{
  echo "MBDSDR submission package"
  echo "generated_utc: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "repo_root    : ${REPO_ROOT}"
  echo "source_of_truth: docs/learn/phase7/paper/main.md (v0.4)"
  echo "note         : refs.bib / final PDF / author block NOT built (see P2-submission-check.md)."
  echo "excluded     : smoke small-N figures (N80/N160/N2/N18/N40) and unreferenced recorded__N5."
  echo "------------------------------------------"
  ( cd "${OUTDIR}" && find sources figures data -type f | sort | while read -r f; do
      sha=$(sha256sum "${f}" | cut -d' ' -f1)
      sz=$(stat -c '%s' "${f}")
      printf "%-58s %10s bytes  %s\n" "${f}" "${sz}" "${sha}"
    done )
} > "${MANIFEST}"

echo "------------------------------------------"
echo "copied=${copied}  missing=${missing}"
echo "manifest: ${MANIFEST}"
if [[ "${missing}" -gt 0 ]]; then
  echo "WARNING: ${missing} expected artifact(s) missing (listed above). Re-run the matching experiments before submission."
fi
