#!/usr/bin/env bash
# =====================================================================
#  MBDSDR paper submission packager (P2, phase 10 -> upgraded phase 11).
#
#  Collects the controlled paper sources + the canonical 10 figures +
#  their CSVs/manifests into one self-contained submission folder, then
#  (phase 11) bundles it into a .zip and offers a --check self-audit.
#
#  DESIGN RULES (red lines):
#   * paper/ (repo root) is gitignored; figures/CSVs are regenerated by
#     the experiments/ scripts and are NOT committed. This script only
#     READS them and copies into an OUT folder the caller chooses.
#   * Only the 10 CANONICAL figures (origin/N/date matching main.md
#     Appendix + main.tex MIGRATE comments) are bundled. Smoke / debug
#     runs (small-N leftovers, e.g. N80/N160/N2/N18/N40) and the
#     unreferenced `recorded__N5` figure are EXCLUDED on purpose.
#   * refs.bib is now present and verified (phase 11, 2026-10-02); it is
#     copied into sources/. The final PDF and the real author block are
#     NOT built here: typesetting needs a TeX env with IEEEtran.cls, and
#     author/affiliation/funding are honest PENDING placeholders.
#
#  Usage:
#     bash tools/paper_package.sh [OUTDIR]          # build folder + MANIFEST + zip
#     bash tools/paper_package.sh --check [OUTDIR]  # self-audit only (no build)
#       OUTDIR default = ./paper_submission_package
#
#  Exit 0 on success (and on self-check PASS); exit 1 on build missing
#  artifacts or on self-check FAIL. Prints a human manifest and writes
#  MANIFEST.txt + SELFCHECK.txt.
# =====================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PAPER_DIR="${REPO_ROOT}/docs/learn/phase7/paper"
FIG_DIR="${REPO_ROOT}/paper/experiments/figures"
CSV_DIR="${REPO_ROOT}/paper/experiments"

MODE="build"
OUTDIR="${REPO_ROOT}/paper_submission_package"
if [[ "${1:-}" == "--check" ]]; then
  MODE="check"; shift
fi
[[ -n "${1:-}" ]] && OUTDIR="$1"

# ---------------------------------------------------------------------
# CANONICAL PACKAGE TABLE (single source for both build and --check).
#   field order: fignum | figfile | expected_N | csvfile | semicolon-sep key CSV columns
#   Tab.Y tables are noted but have no bundled data table yet (PENDING rows
#   in main.tex), so the figure<->CSV chain is what we can deterministically
#   audit today.
# ---------------------------------------------------------------------
PKG_TABLE=(
  "1|ebno_decode_success__synthetic__N2400__20261001.png|2400|ebno_decode_success.csv|success_rate;n_trials;wilson_lo;wilson_hi;data_origin"
  "2|rate_sweep_success__synthetic__N1400__20261002.png|1400|rate_sweep_success.csv|success_rate;n_trials;data_origin"
  "3|rate_bandwidth_success__synthetic__N900__20261001.png|900|rate_bandwidth_success.csv|success_rate;n_trials;data_origin"
  "4|doppler_comp_success__synthetic__N3600__20261002.png|3600|doppler_comp_success.csv|success_rate;n_trials;data_origin"
  "5|baseline_compare_amr__synthetic__N600__20261001.png|600|baseline_compare.csv|classic_acc;knn_acc;llm_agent;data_origin"
  "6|llm_baseline_amr__synthetic__N300__20261001.png|300|llm_baseline.csv|classic_acc;knn_acc;llm_agent;data_origin"
  "7|amr_confusion_matrix__synthetic__N640__20261001.png|640|amr_confusion_matrix_snr10.csv|true\\pred"
  "8|doppler_convergence__synthetic__N155__20261001.png|155|doppler_convergence.csv|pos_err_km;data_origin"
  "9|doppler_duration_convergence__synthetic__N6__20261001.png|6|doppler_duration_convergence.csv|rls_ref_err_km;data_origin"
  "10|agent_toolcall_stages__synthetic__N400__20261002.png|400|agent_toolcall_stage_summary.csv|stage;n;success_rate"
)
# Supporting (non-figure) CSVs + per-run manifests that must also be bundled.
DATA_EXTRA=(
  "manifest_ebno_decode.json"   "manifest_rate_sweep.json"     "manifest_rate_bandwidth.json"
  "manifest_doppler_comp.json"  "manifest_baseline.json"       "manifest_llm_baseline.json"
  "manifest_amr.json"           "manifest_doppler.json"        "manifest_doppler_duration.json"
  "manifest_agent_toolcall.json"
  "agent_toolcall_detail.csv"   "agent_toolcall_requests.csv"
)
# Controlled sources to bundle.
SOURCES=( "main.md" "main.tex" "refs.bib" "CHANGES.md" "README.md" )

# =====================================================================
#  SELF-CHECK MODE
#   audit: main.tex figure references  <->  bundled figure whitelist
#          <->  CSV presence / key columns  <->  filename-N / row-count.
# =====================================================================
run_check() {
  local outdir="$1"
  local report="${outdir}/SELFCHECK.txt"
  mkdir -p "${outdir}"
  local pass=0 fail=0 warn=0
  local -a lines=()
  say(){ lines+=("$1"); }

  say "MBDSDR paper-package SELF-CHECK"
  say "generated_utc: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  say "package_dir  : ${outdir}"
  say "------------------------------------------"

  local tex="${PAPER_DIR}/main.tex"
  local md="${PAPER_DIR}/main.md"

  # --- (A) controlled sources present in repo --------------------------
  say "[A] controlled sources (docs/learn/phase7/paper/):"
  local f
  for f in "${SOURCES[@]}"; do
    if [[ -f "${PAPER_DIR}/${f}" ]]; then
      say "    OK   ${f}"
      pass=$((pass+1))
    else
      say "    FAIL ${f}  (missing)"
      fail=$((fail+1))
    fi
  done

  # --- (B) refs.bib has real entries + honest status comments ----------
  say "[B] refs.bib integrity:"
  local n_entries n_verified n_partial n_unverified
  n_entries=$(grep -cE '^@[a-zA-Z]+\{' "${PAPER_DIR}/refs.bib" || true)
  say "    BibTeX entries: ${n_entries}  (expect >0)"
  if [[ "${n_entries}" -gt 0 ]]; then pass=$((pass+1)); else fail=$((fail+1)); fi
  n_verified=$(grep -c '\[已核验\]' "${PAPER_DIR}/refs.bib" || true)
  n_partial=$(grep -c '\[部分核验\]' "${PAPER_DIR}/refs.bib" || true)
  n_unverified=$(grep -c '\[未核验\]' "${PAPER_DIR}/refs.bib" || true)
  say "    status markers: 已核验=${n_verified} 部分核验=${n_partial} 未核验=${n_unverified} (未核验 comment-only allowed)"
  pass=$((pass+1))

  # --- (C) main.tex references every canonical figure filename ---------
  say "[C] main.tex MIGRATE/ref chain -> bundled figure whitelist:"
  local row fignum fig expN csv cols
  for row in "${PKG_TABLE[@]}"; do
    IFS='|' read -r fignum fig expN csv cols <<< "${row}"
    if grep -qF "${fig}" "${tex}"; then
      say "    OK   Fig.${fignum}  main.tex references '${fig}'"
      pass=$((pass+1))
    else
      say "    FAIL Fig.${fignum}  main.tex does NOT reference '${fig}'"
      fail=$((fail+1))
    fi
    if [[ "${fig}" == *"N${expN}"* ]]; then
      say "    OK   Fig.${fignum}  filename N matches Appendix N=${expN}"
      pass=$((pass+1))
    else
      say "    FAIL Fig.${fignum}  filename lacks N${expN} (got ${fig})"
      fail=$((fail+1))
    fi
  done

  # --- (D) figures + CSVs exist on disk --------------------------------
  say "[D] bundled artifacts present on disk:"
  for row in "${PKG_TABLE[@]}"; do
    IFS='|' read -r fignum fig expN csv cols <<< "${row}"
    [[ -f "${FIG_DIR}/${fig}" ]] && { say "    OK   figures/${fig}"; pass=$((pass+1)); } \
                                 || { say "    FAIL figures/${fig} missing"; fail=$((fail+1)); }
    [[ -f "${CSV_DIR}/${csv}" ]] && { say "    OK   data/${csv}"; pass=$((pass+1)); } \
                                 || { say "    FAIL data/${csv} missing"; fail=$((fail+1)); }
  done

  # --- (E) CSV key columns present -------------------------------------
  say "[E] CSV expected columns:"
  local hdr c
  for row in "${PKG_TABLE[@]}"; do
    IFS='|' read -r fignum fig expN csv cols <<< "${row}"
    if [[ ! -f "${CSV_DIR}/${csv}" ]]; then say "    SKIP Fig.${fignum} ${csv} absent"; warn=$((warn+1)); continue; fi
    hdr="$(head -1 "${CSV_DIR}/${csv}")"
    local missing=""
    IFS=';' read -ra clist <<< "${cols}"
    for c in "${clist[@]}"; do
      grep -qF "${c}" <<< "${hdr}" || missing="${missing} ${c}"
    done
    if [[ -z "${missing}" ]]; then
      say "    OK   Fig.${fignum} ${csv}: all key columns present"
      pass=$((pass+1))
    else
      say "    FAIL Fig.${fignum} ${csv}: missing columns ->${missing}"
      fail=$((fail+1))
    fi
  done

  # --- (F) deterministic row-count == N where the trial unit is a row --
  say "[F] sample-count / row-count consistency (where 1 row = 1 trial):"
  local rows
  rows=$(( $(wc -l < "${CSV_DIR}/doppler_convergence.csv") - 1 ))
  [[ "${rows}" -eq 155 ]] && { say "    OK   doppler_convergence.csv rows=${rows} == N155"; pass=$((pass+1)); } \
                          || { say "    FAIL doppler_convergence.csv rows=${rows} != N155"; fail=$((fail+1)); }
  rows=$(( $(wc -l < "${CSV_DIR}/doppler_duration_convergence.csv") - 1 ))
  [[ "${rows}" -eq 6 ]] && { say "    OK   doppler_duration_convergence.csv rows=${rows} == N6"; pass=$((pass+1)); } \
                        || { say "    FAIL doppler_duration_convergence.csv rows=${rows} != N6"; fail=$((fail+1)); }
  rows=$(( $(wc -l < "${CSV_DIR}/agent_toolcall_detail.csv") - 1 ))
  [[ "${rows}" -eq 400 ]] && { say "    OK   agent_toolcall_detail.csv rows=${rows} == N400"; pass=$((pass+1)); } \
                          || { say "    FAIL agent_toolcall_detail.csv rows=${rows} != N400"; fail=$((fail+1)); }

  # --- (G) main.md Appendix N agrees with table ------------------------
  say "[G] main.md Appendix N cross-check:"
  for row in "${PKG_TABLE[@]}"; do
    IFS='|' read -r fignum fig expN csv cols <<< "${row}"
    if grep -qE "Fig\. ${fignum}[^0-9]*${expN}" "${md}"; then
      say "    OK   Fig.${fignum} Appendix N=${expN}"
      pass=$((pass+1))
    else
      say "    WARN Fig.${fignum} Appendix row/N=${expN} not matched (check manually)"
      warn=$((warn+1))
    fi
  done

  # --- (H) PENDING markers preserved (LLM online / OTA recorded) -------
  say "[H] honest PENDING markers preserved:"
  if grep -q 'PENDING_ONLINE_RUN' "${md}"; then
    say "    OK   main.md keeps PENDING_ONLINE_RUN (LLM arm)"
    pass=$((pass+1))
  else
    say "    FAIL main.md lost PENDING_ONLINE_RUN"
    fail=$((fail+1))
  fi
  say "    NOTE OTA/recorded cell remains an explicit empty state (recorded__N5 figure NOT bundled)."

  say "------------------------------------------"
  say "RESULT: pass=${pass}  fail=${fail}  warn=${warn}"

  printf '%s\n' "${lines[@]}" | tee "${report}"
  echo "self-check report: ${report}"
  if [[ "${fail}" -gt 0 ]]; then
    echo "SELF-CHECK: FAIL (${fail})"
    return 1
  fi
  echo "SELF-CHECK: PASS"
  return 0
}

# =====================================================================
#  BUILD MODE
# =====================================================================
run_build() {
  echo "MBDSDR paper packager"
  echo "  repo root : ${REPO_ROOT}"
  echo "  out dir   : ${OUTDIR}"

  # Fresh, controlled output dir.
  rm -rf "${OUTDIR}"
  mkdir -p "${OUTDIR}/sources" "${OUTDIR}/figures" "${OUTDIR}/data"

  local copied=0 missing=0 row fignum fig expN csv cols f

  # --- 1) controlled sources (tracked in docs/learn/phase7/paper/) -----
  for f in "${SOURCES[@]}"; do
    if [[ -f "${PAPER_DIR}/${f}" ]]; then
      cp -p "${PAPER_DIR}/${f}" "${OUTDIR}/sources/${f}"
      echo "  [src]  sources/${f}"
      copied=$((copied+1))
    else
      echo "  [MISS] sources/${f}"
      missing=$((missing+1))
    fi
  done

  # --- 2) the 10 canonical figures (whitelist from PKG_TABLE) ----------
  for row in "${PKG_TABLE[@]}"; do
    IFS='|' read -r fignum fig expN csv cols <<< "${row}"
    if [[ -f "${FIG_DIR}/${fig}" ]]; then
      cp -p "${FIG_DIR}/${fig}" "${OUTDIR}/figures/${fig}"
      echo "  [fig]  figures/${fig}"
      copied=$((copied+1))
    else
      echo "  [MISS] figures/${fig}  (run the matching experiments/exp_*.py first)"
      missing=$((missing+1))
    fi
    # --- 3a) per-figure CSV -------------------------------------------
    if [[ -f "${CSV_DIR}/${csv}" ]]; then
      cp -p "${CSV_DIR}/${csv}" "${OUTDIR}/data/${csv}"
      echo "  [data] data/${csv}"
      copied=$((copied+1))
    else
      echo "  [MISS] data/${csv}"
      missing=$((missing+1))
    fi
  done

  # --- 3b) supporting manifests + detail CSVs --------------------------
  for d in "${DATA_EXTRA[@]}"; do
    if [[ -f "${CSV_DIR}/${d}" ]]; then
      cp -p "${CSV_DIR}/${d}" "${OUTDIR}/data/${d}"
      echo "  [data] data/${d}"
      copied=$((copied+1))
    else
      echo "  [MISS] data/${d}"
      missing=$((missing+1))
    fi
  done

  # --- 4) MANIFEST.txt --------------------------------------------------
  local MANIFEST="${OUTDIR}/MANIFEST.txt"
  {
    echo "MBDSDR submission package"
    echo "generated_utc: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "repo_root    : ${REPO_ROOT}"
    echo "source_of_truth: docs/learn/phase7/paper/main.md (v0.5)"
    echo "refs.bib     : present (verified 2026-10-02; 7 verified / 5 partial)."
    echo "author block : PENDING placeholders (no fabricated identity/affiliation/funding)."
    echo "excluded     : smoke small-N figures (N80/N160/N2/N18/N40) and unreferenced recorded__N5."
    echo "------------------------------------------"
    ( cd "${OUTDIR}" && find sources figures data -type f | sort | while read -r f; do
        sha=$(sha256sum "${f}" | cut -d' ' -f1)
        sz=$(stat -c '%s' "${f}")
        printf "%-58s %10s bytes  %s\n" "${f}" "${sz}" "${sha}"
      done )
  } > "${MANIFEST}"

  echo "------------------------------------------"
  echo "copied=${copied}  missing=${missing}"
  echo "manifest: ${MANIFEST}"

  # --- 5) self-check then zip ------------------------------------------
  echo "------------------------------------------"
  local sc=0
  run_check "${OUTDIR}" || sc=$?
  if [[ "${sc}" -ne 0 ]]; then
    echo "WARNING: self-check reported failures; see SELFCHECK.txt"
  fi

  local zip="${OUTDIR}.zip"
  rm -f "${zip}"
  if command -v zip >/dev/null 2>&1; then
    ( cd "$(dirname "${OUTDIR}")" && zip -r -q "$(basename "${zip}")" "$(basename "${OUTDIR}")" )
    echo "zip: ${zip}"
  else
    echo "WARN: 'zip' not installed; skipping archive (folder package still built)."
  fi

  if [[ "${missing}" -gt 0 ]]; then
    echo "WARNING: ${missing} expected artifact(s) missing (listed above). Re-run the matching experiments before submission."
  fi
}

if [[ "${MODE}" == "check" ]]; then
  run_check "${OUTDIR}"
else
  run_build
fi
